DROP TABLE IF EXISTS user;
CREATE TABLE user (
id INT NOT NULL AUTO_INCREMENT,
firstName VARCHAR(100) NOT NULL,
lastName VARCHAR(40) NOT NULL,
emailId VARCHAR(100) NOT NULL,
contactNumber VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);